// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFHtOHvg5NtvQQN_Qc0s8-s3g4G9FDC94',
    appId: '1:997263720715:web:e2da61761ff7c12edde20e',
    messagingSenderId: '997263720715',
    projectId: 'ngerekrut',
    authDomain: 'ngerekrut.firebaseapp.com',
    storageBucket: 'ngerekrut.firebasestorage.app',
    measurementId: 'G-TW9N8MJ8SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDYCP31wwk117yPRMkCadh6NVmbmQcvzE',
    appId: '1:997263720715:android:2e1bd5f210bb3b47dde20e',
    messagingSenderId: '997263720715',
    projectId: 'ngerekrut',
    storageBucket: 'ngerekrut.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaorxn9hF-Zqm7XXLzBoZiAr6BmQOJ3Go',
    appId: '1:997263720715:ios:0925194da9c72f41dde20e',
    messagingSenderId: '997263720715',
    projectId: 'ngerekrut',
    storageBucket: 'ngerekrut.firebasestorage.app',
    iosBundleId: 'com.ngerekrut.ngerekrut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaorxn9hF-Zqm7XXLzBoZiAr6BmQOJ3Go',
    appId: '1:997263720715:ios:0925194da9c72f41dde20e',
    messagingSenderId: '997263720715',
    projectId: 'ngerekrut',
    storageBucket: 'ngerekrut.firebasestorage.app',
    iosBundleId: 'com.ngerekrut.ngerekrut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFHtOHvg5NtvQQN_Qc0s8-s3g4G9FDC94',
    appId: '1:997263720715:web:28208097c8118425dde20e',
    messagingSenderId: '997263720715',
    projectId: 'ngerekrut',
    authDomain: 'ngerekrut.firebaseapp.com',
    storageBucket: 'ngerekrut.firebasestorage.app',
    measurementId: 'G-XBZ747FW99',
  );
}
