// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'langchain/chat_models/chat_message_record.dart';
import 'models/recruiter_shortlist_record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 192818138724406839),
    name: 'ChatMessageRecord',
    lastPropertyId: const obx_int.IdUid(9, 7211320712244921855),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4486096757669346649),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7897140007528916518),
        name: 'messageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7513786765870543113),
        name: 'sessionId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8947658321406391850),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8076194560651863931),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2296081089943326958),
        name: 'toolCallId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2914226483797808815),
        name: 'toolCallsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1980748462399766782),
        name: 'customRole',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7211320712244921855),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 3942250377093927904),
    name: 'RecruiterShortlistRecord',
    lastPropertyId: const obx_int.IdUid(9, 1341466104078536359),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 314809207923630999),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4669264022339063678),
        name: 'screeningId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6315619543830011374),
        name: 'jobId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1092589508076213968),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1679749732970520689),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4959888345009046664),
        name: 'rankedCandidatesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3931532207535275999),
        name: 'topCandidatesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2781382479281100873),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1341466104078536359),
        name: 'usedMode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 3942250377093927904),
    lastIndexId: const obx_int.IdUid(10, 8502198300901827169),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      6671613770378980644,
      3771481167136907639,
      604602462602967945,
      8873902695905099242,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      7321281553670282433,
      3706272313851520381,
      4549889876804853519,
      6020046693126939406,
      1708203424266546156,
      1767980893389551358,
      3989367533359699525,
      8057606781533614106,
      3410859472718768378,
      7832942748883753715,
      8618417641717077670,
      9020498126875084071,
      2928340504084804308,
      7860798235639004503,
      7694501788501946898,
      3971290223628064188,
      1986276478004498093,
      4451049728594606965,
      969892726751428890,
      8844568291758900397,
      5038484887291045652,
      3855690217103562002,
      8470091968744341694,
      2566421430921201837,
      4512349858036600612,
      8439705179731743929,
      4850305063538289741,
      3697027191662953051,
      1388097754296658474,
      7198630570270777952,
      5207525822740862074,
      2370715338551868757,
      4914659517885697083,
      2211747628578735823,
      7699944642613597094,
      8623317648174922149,
      4330794384961091333,
      8759241658610005985,
      4128512444098594912,
      6524160172408730722,
      9003624544635338794,
      7707400394331054288,
      8904013953663975119,
      1448300247578670125,
      8449866426002043341,
      4090136038613682916,
      788011157978678040,
      4950799976665734156,
      5098157767805719933,
      3954630399829658470,
      2421495247382426039,
      7043033964983700569,
      234934850642461181,
      4843349229031811443,
      2551999332351935629,
      5297307485412032798,
      633213066595533854,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatMessageRecord: obx_int.EntityDefinition<ChatMessageRecord>(
      model: _entities[0],
      toOneRelations: (ChatMessageRecord object) => [],
      toManyRelations: (ChatMessageRecord object) => {},
      getId: (ChatMessageRecord object) => object.id,
      setId: (ChatMessageRecord object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessageRecord object, fb.Builder fbb) {
        final messageIdOffset = fbb.writeString(object.messageId);
        final sessionIdOffset = fbb.writeString(object.sessionId);
        final roleOffset = fbb.writeString(object.role);
        final contentOffset = fbb.writeString(object.content);
        final toolCallIdOffset = object.toolCallId == null
            ? null
            : fbb.writeString(object.toolCallId!);
        final toolCallsJsonOffset = object.toolCallsJson == null
            ? null
            : fbb.writeString(object.toolCallsJson!);
        final customRoleOffset = object.customRole == null
            ? null
            : fbb.writeString(object.customRole!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, messageIdOffset);
        fbb.addOffset(2, sessionIdOffset);
        fbb.addOffset(3, roleOffset);
        fbb.addOffset(4, contentOffset);
        fbb.addOffset(5, toolCallIdOffset);
        fbb.addOffset(6, toolCallsJsonOffset);
        fbb.addOffset(7, customRoleOffset);
        fbb.addInt64(8, object.createdAt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final messageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final toolCallIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final toolCallsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final customRoleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object = ChatMessageRecord(
          id: idParam,
          messageId: messageIdParam,
          sessionId: sessionIdParam,
          role: roleParam,
          content: contentParam,
          toolCallId: toolCallIdParam,
          toolCallsJson: toolCallsJsonParam,
          customRole: customRoleParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    RecruiterShortlistRecord:
        obx_int.EntityDefinition<RecruiterShortlistRecord>(
          model: _entities[1],
          toOneRelations: (RecruiterShortlistRecord object) => [],
          toManyRelations: (RecruiterShortlistRecord object) => {},
          getId: (RecruiterShortlistRecord object) => object.id,
          setId: (RecruiterShortlistRecord object, int id) {
            object.id = id;
          },
          objectToFB: (RecruiterShortlistRecord object, fb.Builder fbb) {
            final screeningIdOffset = fbb.writeString(object.screeningId);
            final jobIdOffset = fbb.writeString(object.jobId);
            final statusOffset = fbb.writeString(object.status);
            final summaryOffset = fbb.writeString(object.summary);
            final rankedCandidatesJsonOffset = fbb.writeString(
              object.rankedCandidatesJson,
            );
            final topCandidatesJsonOffset = fbb.writeString(
              object.topCandidatesJson,
            );
            final usedModeOffset = object.usedMode == null
                ? null
                : fbb.writeString(object.usedMode!);
            fbb.startTable(10);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, screeningIdOffset);
            fbb.addOffset(2, jobIdOffset);
            fbb.addOffset(3, statusOffset);
            fbb.addOffset(4, summaryOffset);
            fbb.addOffset(5, rankedCandidatesJsonOffset);
            fbb.addOffset(6, topCandidatesJsonOffset);
            fbb.addInt64(7, object.createdAt);
            fbb.addOffset(8, usedModeOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final screeningIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final jobIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final statusParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 10, '');
            final summaryParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 12, '');
            final usedModeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 20);
            final rankedCandidatesJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final topCandidatesJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 16, '');
            final createdAtParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              18,
              0,
            );
            final object = RecruiterShortlistRecord(
              id: idParam,
              screeningId: screeningIdParam,
              jobId: jobIdParam,
              status: statusParam,
              summary: summaryParam,
              usedMode: usedModeParam,
              rankedCandidatesJson: rankedCandidatesJsonParam,
              topCandidatesJson: topCandidatesJsonParam,
              createdAt: createdAtParam,
            );

            return object;
          },
        ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatMessageRecord] entity fields to define ObjectBox queries.
class ChatMessageRecord_ {
  /// See [ChatMessageRecord.id].
  static final id = obx.QueryIntegerProperty<ChatMessageRecord>(
    _entities[0].properties[0],
  );

  /// See [ChatMessageRecord.messageId].
  static final messageId = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[1],
  );

  /// See [ChatMessageRecord.sessionId].
  static final sessionId = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[2],
  );

  /// See [ChatMessageRecord.role].
  static final role = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[3],
  );

  /// See [ChatMessageRecord.content].
  static final content = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[4],
  );

  /// See [ChatMessageRecord.toolCallId].
  static final toolCallId = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[5],
  );

  /// See [ChatMessageRecord.toolCallsJson].
  static final toolCallsJson = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[6],
  );

  /// See [ChatMessageRecord.customRole].
  static final customRole = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[7],
  );

  /// See [ChatMessageRecord.createdAt].
  static final createdAt = obx.QueryIntegerProperty<ChatMessageRecord>(
    _entities[0].properties[8],
  );
}

/// [RecruiterShortlistRecord] entity fields to define ObjectBox queries.
class RecruiterShortlistRecord_ {
  /// See [RecruiterShortlistRecord.id].
  static final id = obx.QueryIntegerProperty<RecruiterShortlistRecord>(
    _entities[1].properties[0],
  );

  /// See [RecruiterShortlistRecord.screeningId].
  static final screeningId = obx.QueryStringProperty<RecruiterShortlistRecord>(
    _entities[1].properties[1],
  );

  /// See [RecruiterShortlistRecord.jobId].
  static final jobId = obx.QueryStringProperty<RecruiterShortlistRecord>(
    _entities[1].properties[2],
  );

  /// See [RecruiterShortlistRecord.status].
  static final status = obx.QueryStringProperty<RecruiterShortlistRecord>(
    _entities[1].properties[3],
  );

  /// See [RecruiterShortlistRecord.summary].
  static final summary = obx.QueryStringProperty<RecruiterShortlistRecord>(
    _entities[1].properties[4],
  );

  /// See [RecruiterShortlistRecord.rankedCandidatesJson].
  static final rankedCandidatesJson =
      obx.QueryStringProperty<RecruiterShortlistRecord>(
        _entities[1].properties[5],
      );

  /// See [RecruiterShortlistRecord.topCandidatesJson].
  static final topCandidatesJson =
      obx.QueryStringProperty<RecruiterShortlistRecord>(
        _entities[1].properties[6],
      );

  /// See [RecruiterShortlistRecord.createdAt].
  static final createdAt = obx.QueryIntegerProperty<RecruiterShortlistRecord>(
    _entities[1].properties[7],
  );

  /// See [RecruiterShortlistRecord.usedMode].
  static final usedMode = obx.QueryStringProperty<RecruiterShortlistRecord>(
    _entities[1].properties[8],
  );
}
