// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'langchain/chat_models/chat_message_record.dart';
import 'models/candidate_scorecard_record.dart';
import 'models/chat_session_record.dart';
import 'models/interview_guide_record.dart';
import 'models/job_application_record.dart';
import 'models/recruiter_shortlist_record.dart';
import 'models/saved_job_record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 192818138724406839),
    name: 'ChatMessageRecord',
    lastPropertyId: const obx_int.IdUid(9, 7211320712244921855),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4486096757669346649),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7897140007528916518),
        name: 'messageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7513786765870543113),
        name: 'sessionId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8947658321406391850),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8076194560651863931),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2296081089943326958),
        name: 'toolCallId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2914226483797808815),
        name: 'toolCallsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1980748462399766782),
        name: 'customRole',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7211320712244921855),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 3942250377093927904),
    name: 'RecruiterShortlistRecord',
    lastPropertyId: const obx_int.IdUid(9, 1341466104078536359),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 314809207923630999),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4669264022339063678),
        name: 'screeningId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6315619543830011374),
        name: 'jobId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1092589508076213968),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1679749732970520689),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4959888345009046664),
        name: 'rankedCandidatesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3931532207535275999),
        name: 'topCandidatesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2781382479281100873),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1341466104078536359),
        name: 'usedMode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 77447243925955203),
    name: 'CandidateScorecardRecord',
    lastPropertyId: const obx_int.IdUid(8, 2835945180572883496),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4770809965175558037),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5652074738406325744),
        name: 'jobId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7347486815145148426),
        name: 'candidateId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6758291099472408),
        name: 'candidateName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8812900862714736210),
        name: 'interviewType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2108219503889777624),
        name: 'scorecardJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 934338309060139229),
        name: 'usedMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2835945180572883496),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 5701768094403887080),
    name: 'InterviewGuideRecord',
    lastPropertyId: const obx_int.IdUid(7, 4996307860294067598),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 368200842257746441),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3487480123981260961),
        name: 'jobId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2464294047583973937),
        name: 'candidateId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4041101307977610241),
        name: 'candidateName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 842484296930620915),
        name: 'guideJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5714351012546157956),
        name: 'usedMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4996307860294067598),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 8967607260130020246),
    name: 'ChatSessionRecord',
    lastPropertyId: const obx_int.IdUid(7, 5541984059238343795),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 506659056169323933),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2898677325535726695),
        name: 'sessionId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7713108390552819652),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1512756073934161880),
        name: 'lastMessagePreview',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5077906503839657356),
        name: 'messageCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6782708655578119262),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5541984059238343795),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 8753400415785169320),
    name: 'JobApplicationRecord',
    lastPropertyId: const obx_int.IdUid(19, 8134297626217473659),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4320094933041828729),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3674675340156147041),
        name: 'applicationId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(11, 5754318438675131230),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7580896115287597358),
        name: 'jobId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5118288345900404187),
        name: 'candidateId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3187979907996451211),
        name: 'jobTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7257436624273006870),
        name: 'location',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2695716536462774063),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5258418491862326362),
        name: 'appliedAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6329393264935253279),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5152481043438295402),
        name: 'expectedSalary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 9055945966930220219),
        name: 'coverLetter',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4322597041198398981),
        name: 'resumeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5890547551757405320),
        name: 'interviewDatesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5842069332054825669),
        name: 'rejectionReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1396507116796187068),
        name: 'recruiterNotes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 5131794101142368024),
        name: 'internalRating',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3652278966804255296),
        name: 'source',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 8134297626217473659),
        name: 'unitLabel',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 2524636071846182983),
    name: 'SavedJobRecord',
    lastPropertyId: const obx_int.IdUid(9, 2305530148128501227),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8548167051006347926),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5820056660641976416),
        name: 'jobId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(12, 1239497679865358941),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6554302879829573653),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7899017750668495203),
        name: 'location',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1500937975424690641),
        name: 'savedAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6945899579934900314),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5532119103100925571),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2305530148128501227),
        name: 'unitLabel',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(12, 2524636071846182983),
    lastIndexId: const obx_int.IdUid(12, 1239497679865358941),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      6671613770378980644,
      3771481167136907639,
      604602462602967945,
      8873902695905099242,
      8969959986745170977,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      7321281553670282433,
      3706272313851520381,
      4549889876804853519,
      6020046693126939406,
      1708203424266546156,
      1767980893389551358,
      3989367533359699525,
      8057606781533614106,
      3410859472718768378,
      7832942748883753715,
      8618417641717077670,
      9020498126875084071,
      2928340504084804308,
      7860798235639004503,
      7694501788501946898,
      3971290223628064188,
      1986276478004498093,
      4451049728594606965,
      969892726751428890,
      8844568291758900397,
      5038484887291045652,
      3855690217103562002,
      8470091968744341694,
      2566421430921201837,
      4512349858036600612,
      8439705179731743929,
      4850305063538289741,
      3697027191662953051,
      1388097754296658474,
      7198630570270777952,
      5207525822740862074,
      2370715338551868757,
      4914659517885697083,
      2211747628578735823,
      7699944642613597094,
      8623317648174922149,
      4330794384961091333,
      8759241658610005985,
      4128512444098594912,
      6524160172408730722,
      9003624544635338794,
      7707400394331054288,
      8904013953663975119,
      1448300247578670125,
      8449866426002043341,
      4090136038613682916,
      788011157978678040,
      4950799976665734156,
      5098157767805719933,
      3954630399829658470,
      2421495247382426039,
      7043033964983700569,
      234934850642461181,
      4843349229031811443,
      2551999332351935629,
      5297307485412032798,
      633213066595533854,
      800037097158100694,
      3061842719188420887,
      2754621188149784392,
      624823159226967746,
      6639824955790379300,
      509033731412474970,
      862298806667932958,
      236271528955060177,
      7906702866460494364,
      5809072660839361631,
      2790596112990012937,
      6333612683802961927,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatMessageRecord: obx_int.EntityDefinition<ChatMessageRecord>(
      model: _entities[0],
      toOneRelations: (ChatMessageRecord object) => [],
      toManyRelations: (ChatMessageRecord object) => {},
      getId: (ChatMessageRecord object) => object.id,
      setId: (ChatMessageRecord object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessageRecord object, fb.Builder fbb) {
        final messageIdOffset = fbb.writeString(object.messageId);
        final sessionIdOffset = fbb.writeString(object.sessionId);
        final roleOffset = fbb.writeString(object.role);
        final contentOffset = fbb.writeString(object.content);
        final toolCallIdOffset = object.toolCallId == null
            ? null
            : fbb.writeString(object.toolCallId!);
        final toolCallsJsonOffset = object.toolCallsJson == null
            ? null
            : fbb.writeString(object.toolCallsJson!);
        final customRoleOffset = object.customRole == null
            ? null
            : fbb.writeString(object.customRole!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, messageIdOffset);
        fbb.addOffset(2, sessionIdOffset);
        fbb.addOffset(3, roleOffset);
        fbb.addOffset(4, contentOffset);
        fbb.addOffset(5, toolCallIdOffset);
        fbb.addOffset(6, toolCallsJsonOffset);
        fbb.addOffset(7, customRoleOffset);
        fbb.addInt64(8, object.createdAt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final messageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final toolCallIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final toolCallsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final customRoleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object = ChatMessageRecord(
          id: idParam,
          messageId: messageIdParam,
          sessionId: sessionIdParam,
          role: roleParam,
          content: contentParam,
          toolCallId: toolCallIdParam,
          toolCallsJson: toolCallsJsonParam,
          customRole: customRoleParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    RecruiterShortlistRecord:
        obx_int.EntityDefinition<RecruiterShortlistRecord>(
          model: _entities[1],
          toOneRelations: (RecruiterShortlistRecord object) => [],
          toManyRelations: (RecruiterShortlistRecord object) => {},
          getId: (RecruiterShortlistRecord object) => object.id,
          setId: (RecruiterShortlistRecord object, int id) {
            object.id = id;
          },
          objectToFB: (RecruiterShortlistRecord object, fb.Builder fbb) {
            final screeningIdOffset = fbb.writeString(object.screeningId);
            final jobIdOffset = fbb.writeString(object.jobId);
            final statusOffset = fbb.writeString(object.status);
            final summaryOffset = fbb.writeString(object.summary);
            final rankedCandidatesJsonOffset = fbb.writeString(
              object.rankedCandidatesJson,
            );
            final topCandidatesJsonOffset = fbb.writeString(
              object.topCandidatesJson,
            );
            final usedModeOffset = object.usedMode == null
                ? null
                : fbb.writeString(object.usedMode!);
            fbb.startTable(10);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, screeningIdOffset);
            fbb.addOffset(2, jobIdOffset);
            fbb.addOffset(3, statusOffset);
            fbb.addOffset(4, summaryOffset);
            fbb.addOffset(5, rankedCandidatesJsonOffset);
            fbb.addOffset(6, topCandidatesJsonOffset);
            fbb.addInt64(7, object.createdAt);
            fbb.addOffset(8, usedModeOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final screeningIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final jobIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final statusParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 10, '');
            final summaryParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 12, '');
            final usedModeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 20);
            final rankedCandidatesJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final topCandidatesJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 16, '');
            final createdAtParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              18,
              0,
            );
            final object = RecruiterShortlistRecord(
              id: idParam,
              screeningId: screeningIdParam,
              jobId: jobIdParam,
              status: statusParam,
              summary: summaryParam,
              usedMode: usedModeParam,
              rankedCandidatesJson: rankedCandidatesJsonParam,
              topCandidatesJson: topCandidatesJsonParam,
              createdAt: createdAtParam,
            );

            return object;
          },
        ),
    CandidateScorecardRecord:
        obx_int.EntityDefinition<CandidateScorecardRecord>(
          model: _entities[2],
          toOneRelations: (CandidateScorecardRecord object) => [],
          toManyRelations: (CandidateScorecardRecord object) => {},
          getId: (CandidateScorecardRecord object) => object.id,
          setId: (CandidateScorecardRecord object, int id) {
            object.id = id;
          },
          objectToFB: (CandidateScorecardRecord object, fb.Builder fbb) {
            final jobIdOffset = fbb.writeString(object.jobId);
            final candidateIdOffset = fbb.writeString(object.candidateId);
            final candidateNameOffset = fbb.writeString(object.candidateName);
            final interviewTypeOffset = fbb.writeString(object.interviewType);
            final scorecardJsonOffset = fbb.writeString(object.scorecardJson);
            final usedModeOffset = object.usedMode == null
                ? null
                : fbb.writeString(object.usedMode!);
            fbb.startTable(9);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, jobIdOffset);
            fbb.addOffset(2, candidateIdOffset);
            fbb.addOffset(3, candidateNameOffset);
            fbb.addOffset(4, interviewTypeOffset);
            fbb.addOffset(5, scorecardJsonOffset);
            fbb.addOffset(6, usedModeOffset);
            fbb.addInt64(7, object.createdAt);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final jobIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final candidateIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final candidateNameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 10, '');
            final interviewTypeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 12, '');
            final scorecardJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final usedModeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 16);
            final createdAtParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              18,
              0,
            );
            final object = CandidateScorecardRecord(
              id: idParam,
              jobId: jobIdParam,
              candidateId: candidateIdParam,
              candidateName: candidateNameParam,
              interviewType: interviewTypeParam,
              scorecardJson: scorecardJsonParam,
              usedMode: usedModeParam,
              createdAt: createdAtParam,
            );

            return object;
          },
        ),
    InterviewGuideRecord: obx_int.EntityDefinition<InterviewGuideRecord>(
      model: _entities[3],
      toOneRelations: (InterviewGuideRecord object) => [],
      toManyRelations: (InterviewGuideRecord object) => {},
      getId: (InterviewGuideRecord object) => object.id,
      setId: (InterviewGuideRecord object, int id) {
        object.id = id;
      },
      objectToFB: (InterviewGuideRecord object, fb.Builder fbb) {
        final jobIdOffset = fbb.writeString(object.jobId);
        final candidateIdOffset = fbb.writeString(object.candidateId);
        final candidateNameOffset = fbb.writeString(object.candidateName);
        final guideJsonOffset = fbb.writeString(object.guideJson);
        final usedModeOffset = object.usedMode == null
            ? null
            : fbb.writeString(object.usedMode!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, jobIdOffset);
        fbb.addOffset(2, candidateIdOffset);
        fbb.addOffset(3, candidateNameOffset);
        fbb.addOffset(4, guideJsonOffset);
        fbb.addOffset(5, usedModeOffset);
        fbb.addInt64(6, object.createdAt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final jobIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final candidateIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final candidateNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final guideJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final usedModeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = InterviewGuideRecord(
          id: idParam,
          jobId: jobIdParam,
          candidateId: candidateIdParam,
          candidateName: candidateNameParam,
          guideJson: guideJsonParam,
          usedMode: usedModeParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    ChatSessionRecord: obx_int.EntityDefinition<ChatSessionRecord>(
      model: _entities[4],
      toOneRelations: (ChatSessionRecord object) => [],
      toManyRelations: (ChatSessionRecord object) => {},
      getId: (ChatSessionRecord object) => object.id,
      setId: (ChatSessionRecord object, int id) {
        object.id = id;
      },
      objectToFB: (ChatSessionRecord object, fb.Builder fbb) {
        final sessionIdOffset = fbb.writeString(object.sessionId);
        final titleOffset = fbb.writeString(object.title);
        final lastMessagePreviewOffset = fbb.writeString(
          object.lastMessagePreview,
        );
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sessionIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, lastMessagePreviewOffset);
        fbb.addInt64(4, object.messageCount);
        fbb.addInt64(5, object.createdAt);
        fbb.addInt64(6, object.updatedAt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final lastMessagePreviewParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final messageCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final updatedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = ChatSessionRecord(
          id: idParam,
          sessionId: sessionIdParam,
          title: titleParam,
          lastMessagePreview: lastMessagePreviewParam,
          messageCount: messageCountParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    JobApplicationRecord: obx_int.EntityDefinition<JobApplicationRecord>(
      model: _entities[5],
      toOneRelations: (JobApplicationRecord object) => [],
      toManyRelations: (JobApplicationRecord object) => {},
      getId: (JobApplicationRecord object) => object.id,
      setId: (JobApplicationRecord object, int id) {
        object.id = id;
      },
      objectToFB: (JobApplicationRecord object, fb.Builder fbb) {
        final applicationIdOffset = fbb.writeString(object.applicationId);
        final jobIdOffset = fbb.writeString(object.jobId);
        final candidateIdOffset = object.candidateId == null
            ? null
            : fbb.writeString(object.candidateId!);
        final jobTitleOffset = fbb.writeString(object.jobTitle);
        final locationOffset = object.location == null
            ? null
            : fbb.writeString(object.location!);
        final statusOffset = fbb.writeString(object.status);
        final expectedSalaryOffset = object.expectedSalary == null
            ? null
            : fbb.writeString(object.expectedSalary!);
        final coverLetterOffset = object.coverLetter == null
            ? null
            : fbb.writeString(object.coverLetter!);
        final resumeIdOffset = object.resumeId == null
            ? null
            : fbb.writeString(object.resumeId!);
        final interviewDatesJsonOffset = object.interviewDatesJson == null
            ? null
            : fbb.writeString(object.interviewDatesJson!);
        final rejectionReasonOffset = object.rejectionReason == null
            ? null
            : fbb.writeString(object.rejectionReason!);
        final recruiterNotesOffset = object.recruiterNotes == null
            ? null
            : fbb.writeString(object.recruiterNotes!);
        final sourceOffset = object.source == null
            ? null
            : fbb.writeString(object.source!);
        final unitLabelOffset = object.unitLabel == null
            ? null
            : fbb.writeString(object.unitLabel!);
        fbb.startTable(20);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, applicationIdOffset);
        fbb.addOffset(2, jobIdOffset);
        fbb.addOffset(3, candidateIdOffset);
        fbb.addOffset(4, jobTitleOffset);
        fbb.addOffset(6, locationOffset);
        fbb.addOffset(7, statusOffset);
        fbb.addInt64(8, object.appliedAt);
        fbb.addInt64(9, object.updatedAt);
        fbb.addOffset(10, expectedSalaryOffset);
        fbb.addOffset(11, coverLetterOffset);
        fbb.addOffset(12, resumeIdOffset);
        fbb.addOffset(13, interviewDatesJsonOffset);
        fbb.addOffset(14, rejectionReasonOffset);
        fbb.addOffset(15, recruiterNotesOffset);
        fbb.addInt64(16, object.internalRating);
        fbb.addOffset(17, sourceOffset);
        fbb.addOffset(18, unitLabelOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final applicationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final jobIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final candidateIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final jobTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final unitLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final locationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final appliedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final updatedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final expectedSalaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final coverLetterParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final resumeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final interviewDatesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final rejectionReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final recruiterNotesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final internalRatingParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          36,
        );
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final object = JobApplicationRecord(
          id: idParam,
          applicationId: applicationIdParam,
          jobId: jobIdParam,
          candidateId: candidateIdParam,
          jobTitle: jobTitleParam,
          unitLabel: unitLabelParam,
          location: locationParam,
          status: statusParam,
          appliedAt: appliedAtParam,
          updatedAt: updatedAtParam,
          expectedSalary: expectedSalaryParam,
          coverLetter: coverLetterParam,
          resumeId: resumeIdParam,
          interviewDatesJson: interviewDatesJsonParam,
          rejectionReason: rejectionReasonParam,
          recruiterNotes: recruiterNotesParam,
          internalRating: internalRatingParam,
          source: sourceParam,
        );

        return object;
      },
    ),
    SavedJobRecord: obx_int.EntityDefinition<SavedJobRecord>(
      model: _entities[6],
      toOneRelations: (SavedJobRecord object) => [],
      toManyRelations: (SavedJobRecord object) => {},
      getId: (SavedJobRecord object) => object.id,
      setId: (SavedJobRecord object, int id) {
        object.id = id;
      },
      objectToFB: (SavedJobRecord object, fb.Builder fbb) {
        final jobIdOffset = fbb.writeString(object.jobId);
        final titleOffset = fbb.writeString(object.title);
        final locationOffset = object.location == null
            ? null
            : fbb.writeString(object.location!);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final unitLabelOffset = object.unitLabel == null
            ? null
            : fbb.writeString(object.unitLabel!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, jobIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(4, locationOffset);
        fbb.addInt64(5, object.savedAt);
        fbb.addOffset(6, notesOffset);
        fbb.addBool(7, object.isActive);
        fbb.addOffset(8, unitLabelOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final jobIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final unitLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final locationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final savedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = SavedJobRecord(
          id: idParam,
          jobId: jobIdParam,
          title: titleParam,
          unitLabel: unitLabelParam,
          location: locationParam,
          savedAt: savedAtParam,
          notes: notesParam,
          isActive: isActiveParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatMessageRecord] entity fields to define ObjectBox queries.
class ChatMessageRecord_ {
  /// See [ChatMessageRecord.id].
  static final id = obx.QueryIntegerProperty<ChatMessageRecord>(
    _entities[0].properties[0],
  );

  /// See [ChatMessageRecord.messageId].
  static final messageId = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[1],
  );

  /// See [ChatMessageRecord.sessionId].
  static final sessionId = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[2],
  );

  /// See [ChatMessageRecord.role].
  static final role = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[3],
  );

  /// See [ChatMessageRecord.content].
  static final content = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[4],
  );

  /// See [ChatMessageRecord.toolCallId].
  static final toolCallId = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[5],
  );

  /// See [ChatMessageRecord.toolCallsJson].
  static final toolCallsJson = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[6],
  );

  /// See [ChatMessageRecord.customRole].
  static final customRole = obx.QueryStringProperty<ChatMessageRecord>(
    _entities[0].properties[7],
  );

  /// See [ChatMessageRecord.createdAt].
  static final createdAt = obx.QueryIntegerProperty<ChatMessageRecord>(
    _entities[0].properties[8],
  );
}

/// [RecruiterShortlistRecord] entity fields to define ObjectBox queries.
class RecruiterShortlistRecord_ {
  /// See [RecruiterShortlistRecord.id].
  static final id = obx.QueryIntegerProperty<RecruiterShortlistRecord>(
    _entities[1].properties[0],
  );

  /// See [RecruiterShortlistRecord.screeningId].
  static final screeningId = obx.QueryStringProperty<RecruiterShortlistRecord>(
    _entities[1].properties[1],
  );

  /// See [RecruiterShortlistRecord.jobId].
  static final jobId = obx.QueryStringProperty<RecruiterShortlistRecord>(
    _entities[1].properties[2],
  );

  /// See [RecruiterShortlistRecord.status].
  static final status = obx.QueryStringProperty<RecruiterShortlistRecord>(
    _entities[1].properties[3],
  );

  /// See [RecruiterShortlistRecord.summary].
  static final summary = obx.QueryStringProperty<RecruiterShortlistRecord>(
    _entities[1].properties[4],
  );

  /// See [RecruiterShortlistRecord.rankedCandidatesJson].
  static final rankedCandidatesJson =
      obx.QueryStringProperty<RecruiterShortlistRecord>(
        _entities[1].properties[5],
      );

  /// See [RecruiterShortlistRecord.topCandidatesJson].
  static final topCandidatesJson =
      obx.QueryStringProperty<RecruiterShortlistRecord>(
        _entities[1].properties[6],
      );

  /// See [RecruiterShortlistRecord.createdAt].
  static final createdAt = obx.QueryIntegerProperty<RecruiterShortlistRecord>(
    _entities[1].properties[7],
  );

  /// See [RecruiterShortlistRecord.usedMode].
  static final usedMode = obx.QueryStringProperty<RecruiterShortlistRecord>(
    _entities[1].properties[8],
  );
}

/// [CandidateScorecardRecord] entity fields to define ObjectBox queries.
class CandidateScorecardRecord_ {
  /// See [CandidateScorecardRecord.id].
  static final id = obx.QueryIntegerProperty<CandidateScorecardRecord>(
    _entities[2].properties[0],
  );

  /// See [CandidateScorecardRecord.jobId].
  static final jobId = obx.QueryStringProperty<CandidateScorecardRecord>(
    _entities[2].properties[1],
  );

  /// See [CandidateScorecardRecord.candidateId].
  static final candidateId = obx.QueryStringProperty<CandidateScorecardRecord>(
    _entities[2].properties[2],
  );

  /// See [CandidateScorecardRecord.candidateName].
  static final candidateName =
      obx.QueryStringProperty<CandidateScorecardRecord>(
        _entities[2].properties[3],
      );

  /// See [CandidateScorecardRecord.interviewType].
  static final interviewType =
      obx.QueryStringProperty<CandidateScorecardRecord>(
        _entities[2].properties[4],
      );

  /// See [CandidateScorecardRecord.scorecardJson].
  static final scorecardJson =
      obx.QueryStringProperty<CandidateScorecardRecord>(
        _entities[2].properties[5],
      );

  /// See [CandidateScorecardRecord.usedMode].
  static final usedMode = obx.QueryStringProperty<CandidateScorecardRecord>(
    _entities[2].properties[6],
  );

  /// See [CandidateScorecardRecord.createdAt].
  static final createdAt = obx.QueryIntegerProperty<CandidateScorecardRecord>(
    _entities[2].properties[7],
  );
}

/// [InterviewGuideRecord] entity fields to define ObjectBox queries.
class InterviewGuideRecord_ {
  /// See [InterviewGuideRecord.id].
  static final id = obx.QueryIntegerProperty<InterviewGuideRecord>(
    _entities[3].properties[0],
  );

  /// See [InterviewGuideRecord.jobId].
  static final jobId = obx.QueryStringProperty<InterviewGuideRecord>(
    _entities[3].properties[1],
  );

  /// See [InterviewGuideRecord.candidateId].
  static final candidateId = obx.QueryStringProperty<InterviewGuideRecord>(
    _entities[3].properties[2],
  );

  /// See [InterviewGuideRecord.candidateName].
  static final candidateName = obx.QueryStringProperty<InterviewGuideRecord>(
    _entities[3].properties[3],
  );

  /// See [InterviewGuideRecord.guideJson].
  static final guideJson = obx.QueryStringProperty<InterviewGuideRecord>(
    _entities[3].properties[4],
  );

  /// See [InterviewGuideRecord.usedMode].
  static final usedMode = obx.QueryStringProperty<InterviewGuideRecord>(
    _entities[3].properties[5],
  );

  /// See [InterviewGuideRecord.createdAt].
  static final createdAt = obx.QueryIntegerProperty<InterviewGuideRecord>(
    _entities[3].properties[6],
  );
}

/// [ChatSessionRecord] entity fields to define ObjectBox queries.
class ChatSessionRecord_ {
  /// See [ChatSessionRecord.id].
  static final id = obx.QueryIntegerProperty<ChatSessionRecord>(
    _entities[4].properties[0],
  );

  /// See [ChatSessionRecord.sessionId].
  static final sessionId = obx.QueryStringProperty<ChatSessionRecord>(
    _entities[4].properties[1],
  );

  /// See [ChatSessionRecord.title].
  static final title = obx.QueryStringProperty<ChatSessionRecord>(
    _entities[4].properties[2],
  );

  /// See [ChatSessionRecord.lastMessagePreview].
  static final lastMessagePreview = obx.QueryStringProperty<ChatSessionRecord>(
    _entities[4].properties[3],
  );

  /// See [ChatSessionRecord.messageCount].
  static final messageCount = obx.QueryIntegerProperty<ChatSessionRecord>(
    _entities[4].properties[4],
  );

  /// See [ChatSessionRecord.createdAt].
  static final createdAt = obx.QueryIntegerProperty<ChatSessionRecord>(
    _entities[4].properties[5],
  );

  /// See [ChatSessionRecord.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<ChatSessionRecord>(
    _entities[4].properties[6],
  );
}

/// [JobApplicationRecord] entity fields to define ObjectBox queries.
class JobApplicationRecord_ {
  /// See [JobApplicationRecord.id].
  static final id = obx.QueryIntegerProperty<JobApplicationRecord>(
    _entities[5].properties[0],
  );

  /// See [JobApplicationRecord.applicationId].
  static final applicationId = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[1],
  );

  /// See [JobApplicationRecord.jobId].
  static final jobId = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[2],
  );

  /// See [JobApplicationRecord.candidateId].
  static final candidateId = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[3],
  );

  /// See [JobApplicationRecord.jobTitle].
  static final jobTitle = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[4],
  );

  /// See [JobApplicationRecord.location].
  static final location = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[5],
  );

  /// See [JobApplicationRecord.status].
  static final status = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[6],
  );

  /// See [JobApplicationRecord.appliedAt].
  static final appliedAt = obx.QueryIntegerProperty<JobApplicationRecord>(
    _entities[5].properties[7],
  );

  /// See [JobApplicationRecord.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<JobApplicationRecord>(
    _entities[5].properties[8],
  );

  /// See [JobApplicationRecord.expectedSalary].
  static final expectedSalary = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[9],
  );

  /// See [JobApplicationRecord.coverLetter].
  static final coverLetter = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[10],
  );

  /// See [JobApplicationRecord.resumeId].
  static final resumeId = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[11],
  );

  /// See [JobApplicationRecord.interviewDatesJson].
  static final interviewDatesJson =
      obx.QueryStringProperty<JobApplicationRecord>(
        _entities[5].properties[12],
      );

  /// See [JobApplicationRecord.rejectionReason].
  static final rejectionReason = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[13],
  );

  /// See [JobApplicationRecord.recruiterNotes].
  static final recruiterNotes = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[14],
  );

  /// See [JobApplicationRecord.internalRating].
  static final internalRating = obx.QueryIntegerProperty<JobApplicationRecord>(
    _entities[5].properties[15],
  );

  /// See [JobApplicationRecord.source].
  static final source = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[16],
  );

  /// See [JobApplicationRecord.unitLabel].
  static final unitLabel = obx.QueryStringProperty<JobApplicationRecord>(
    _entities[5].properties[17],
  );
}

/// [SavedJobRecord] entity fields to define ObjectBox queries.
class SavedJobRecord_ {
  /// See [SavedJobRecord.id].
  static final id = obx.QueryIntegerProperty<SavedJobRecord>(
    _entities[6].properties[0],
  );

  /// See [SavedJobRecord.jobId].
  static final jobId = obx.QueryStringProperty<SavedJobRecord>(
    _entities[6].properties[1],
  );

  /// See [SavedJobRecord.title].
  static final title = obx.QueryStringProperty<SavedJobRecord>(
    _entities[6].properties[2],
  );

  /// See [SavedJobRecord.location].
  static final location = obx.QueryStringProperty<SavedJobRecord>(
    _entities[6].properties[3],
  );

  /// See [SavedJobRecord.savedAt].
  static final savedAt = obx.QueryIntegerProperty<SavedJobRecord>(
    _entities[6].properties[4],
  );

  /// See [SavedJobRecord.notes].
  static final notes = obx.QueryStringProperty<SavedJobRecord>(
    _entities[6].properties[5],
  );

  /// See [SavedJobRecord.isActive].
  static final isActive = obx.QueryBooleanProperty<SavedJobRecord>(
    _entities[6].properties[6],
  );

  /// See [SavedJobRecord.unitLabel].
  static final unitLabel = obx.QueryStringProperty<SavedJobRecord>(
    _entities[6].properties[7],
  );
}
